### ISSUE TITLE
关于拖拽悬浮窗代码修改

### ISSUE THREAD

**Issue by YuPf1989** [24Kshign/SuspensionWindow#1]
小浮窗的拖拽存在点小bug，在setOnTouchListener中的ACTION_MOVE  params.y应做如下修改：
// 获取系统状态栏的高度
        int resourceId = getResources().getIdentifier("status_bar_height", "dimen", "android");
        if (resourceId > 0) {
            statusBarHeight = this.getResources().getDimensionPixelSize(resourceId);
        }
          case MotionEvent.ACTION_MOVE:
                        params.x = (int) (event.getRawX() - startX);
                        params.y = (int) (event.getRawY() - startY - statusBarHeight);
                        updateViewLayout();
                        break;

**Comment by 24Kshign** [comment]
@YuPf1989 嗯，我知道是什么问题了，感谢
