### ISSUE TITLE
点击开启悬浮窗，自动返回到列表页，此时拖动不会出现下面的删除，并且点击事件跟touch事件冲突

### ISSUE THREAD

**Issue by eicky** [24Kshign/SuspensionWindow#4]
点击开启悬浮窗，自动返回到列表页，此时拖动不会出现下面的删除，红色区域不会出现，第二次拖动就出现了，并且点击事件跟touch事件冲突，无法响应点击事件

**Comment by 24Kshign** [comment]
@eicky 刚才试了一下，貌似没有发现你说的这个问题，方便说一下手机参数吗

**Comment by eicky** [comment]
华为v10, 系统是8.0.0

**Comment by 24Kshign** [comment]
@eicky 已修复，请拉最新代码再试一下，完事之后方便的话可以给我一个反馈，谢谢

**Comment by eicky** [comment]
还存在bug，事件冲突

**Comment by eicky** [comment]
有没QQ或者邮箱，我给你录个小视频

**Comment by 24Kshign** [comment]
@eicky lovecyg123微信
